#!/usr/bin/with-contenv bash

  #Check to make sure the subdomain and token are set
if [ -z "$SUBDOMAINS" ] || [ -z "$TOKEN" ]; then
  echo "Please pass both your subdomain(s) and token as environment variables in your docker run command. See docker info for more details."
  exit 1
else
  echo "Retrieving subdomain and token from the environment variables"
  echo -e "SUBDOMAINS=\"${SUBDOMAINS}\" TOKEN=\"${TOKEN}\"" > /app/duck.conf
fi

# Check to make sure updates are enabled for IPV4 and/or IPV6
if [ "$IPV4" = "false" ] && [ "$IPV6" != "true" ]; then
  echo "Please enable updates for either or both IPv4 and IPv6."
  exit 1
fi

# Check if IPv4 should be updated
# IPv4 updates are enabled by default
if [ "$IPV4" = "false" ]; then
  echo -e "IPV4=\"false\"" >> /app/duck.conf
  echo "IPv4 will not be updated"
else
  echo "IPv4 will be updated"
fi

# Check if IPv6 should be updated
# IPv6 updates are disabled by default
if [ "$IPV6" = "true" ]; then
  echo "IPv6 will be updated"
else
  echo -e "IPV6=\"false\"" >> /app/duck.conf
  echo "IPv6 will not be updated"
fi

# modify crontab if logging to file
if [ "$LOG_FILE" = "true" ]; then
  crontab -u abc /defaults/duckcron
  echo "log will be output to file"
else
  echo "log will be output to docker log"
fi

# permissions
chown -R abc:abc \
	/app \
	/config

# run initial IP update
exec \
	s6-setuidgid abc /app/duck.sh
